#добавить опись перменных
- name: massege
  hosts: APP_MASTER
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  tasks:
    - name: "Ansible | Print multiple variable"
      debug:
          msg:
            - "Обновление CM: {{cm}}"
            - "Обновление MA: {{ma}}"
            - "Обновление MAR: {{mar}}"
            - "имя службы на мастере wf: {{ name_servise_wf_claster_mansger }}"
            - "имя службы на пользовательск их WF: {{ name_servise_wf }}"
            - "имя службы wildfly для менджера агентов: {{ name_servise_wf_ma }}"
            - "имя службв wildfly для mar: {{ name_servise_mar }}"
            - "юзер под которым снимаем дамп: {{ user_posgres }}"
            - "имя базы cm6: {{ dbcm6 }}"
            - "имя базы cmj: {{ dbcmj }}"
            - "имя базы ma: {{ dbma }}"
            - "имя базы mar: {{ dbmar }}"

#tasks:
#- fail: msg="The variable 'bar' is empty"
#  when: bar|length == 0

#- shell: echo "The variable 'foo' is not empty": '{{ foo }}'
#  when: foo|length > 0

- name: Wildfly master stop
  hosts: APP_MASTER
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy: "{{cm}}"
  tasks:
    - name: wf stop
      service: name={{name_servise_wf_claster_mansger}} state=stopped
      when: destroy

    - name: wf igonor
      debug:
        msg:
          - "Отсановка игнорируеться"
      when: not destroy

- name: Wildfly slave stop
  hosts: APP
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy: "{{cm}}"
  tasks:
    - name: wf stop
      service: name={{name_servise_wf}} state=stopped

    - name: wf igonor
      debug:
        msg:
          - "Отсановка игнорируеться"
      when: not destroy

- name: ma stop
  hosts: MA
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy_ma: "{{ma}}"
  tasks:
    - name: ma stop
      service: name={{name_servise_wf_ma}} state=stopped
      when: destroy_ma

    - name: wf_ma igonor
      debug:
        msg:
          - "Отсановка ma игнорируеться"
      when: not destroy_ma

- name: mar stop
  hosts: MAR
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy_mar: "{{mar}}"
  tasks:
    - name: mar stop
      service: name={{name_servise_mar}} state=stopped
      when: destroy_mar

    - name: wf_mar igonor
      debug:
        msg:
          - "Отсановка mar игнорируеться"
      when: not destroy_mar

- name: start pg_dump cm6
  hosts: APP_MASTER
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy: "{{cm}}"

  tasks:
    - name: PG_DUMP_CM5
      become: yes
      become_user: "{{user_posgres}}"
      shell: "pg_dump --port={{ cm6_db_settings_default_PORT }} --username='{{ cm6_db_settings_default_USER  }}' --role 'postgres' --format directory --blobs --no-privileges --no-tablespaces --verbose --no-unlogged-table-data --jobs='{{ cm6_db_settings_default_JOBS }}' --dbname='{{ cm6_db_settings_default_NAME }}' --file '{{CM5_PG_DIR}}/CM5-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}'"
      when: destroy

    - name: PG_DUMP_CM5 igonor
      debug:
        msg:
          - "Создание дампа для Cm6 игнорируется"
      when: not destroy

- hosts: BD_CMJ
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy: "{{cm}}"

  tasks:
    - name: PG_DUMP_CMJ
      become: yes
      become_user: "{{user_posgres}}"
      shell: "pg_dump --port={{ cmj_db_settings_default_PORT }} --username'{{ cmj_db_settings_default_USER  }}' --role 'postgres' --format directory --blobs --no-privileges --no-tablespaces --verbose --no-unlogged-table-data --jobs='{{ cmj_db_settings_default_JOBS }}' --dbname='{{ cmj_db_settings_default_NAME }}' --file '{{CMJ_PG_DIR}}/CMJ-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}'"
      when: destroy

    - name: PG_DUMP_CM5 igonor
      debug:
        msg:
          - "Создание дампа для CMJ игнорируется"
      when: not destroy

- name: start pg_dump MA
  hosts: BD_MA
  user: root
  vars_files: ~/ansible/common/vars/global.yml
  vars:
    destroy_mar: "{{ma}}"

  tasks:
    - name: PG_DUMP_MA
      become: yes
      become_user: "{{user_posgres}}"
      shell: "pg_dump --port={{ cm6_db_settings_default_PORT }} --username'{{ cm6_db_settings_default_USER  }}' --role 'postgres' --format directory --blobs --no-privileges --no-tablespaces --verbose --no-unlogged-table-data --jobs='{{ cm6_db_settings_default_JOBS }}' --dbname='{{ cm6_db_settings_default_NAME }}' --file '{{CM5_PG_DIR}}/MA-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}'"
      when: destroy_mar

    - name: PG_DUMP_MA igonor
      debug:
        msg:
          - "Создание дампа для MA игнорируется"
      when: not destroy_mar